### ISSUE TITLE
Could we have something like do if?

### ISSUE THREAD

**Issue by kasperpeulen** [tc39/proposal-do-expressions#7] opened 2017-10-03 19:43 UTC
The template example seems (unncessary?) verbose to me: 

```javascript
return (
  <nav>
    <Home />
    {
      do {
        if (loggedIn) {
          <LogoutButton />
        } else {
          <LoginButton />
        }
      }
    }
  </nav>
)
```

Could we allow for something like this?

```javascript
return (
  <nav>
    <Home />
    {do if (loggedIn) {
      <LogoutButton />
    } else {
      <LoginButton />
    }}
  </nav>
)
```

**Comment by domenic** [comment] 2017-10-03 20:01
Dupe of #1

**Closed** 2017-11-08 12:19 UTC
